[package]
name = "mosaic-rs"
version = "2.0.0"
edition = "2024"

[profile.dev.package."*"] #otherwise it's crazy slow
opt-level = 3

[profile.release] 
lto = "thin"
strip = true 
debug = true

[dependencies]
##rust stuff
#error handling
anyhow = { version = "1.0.104", default-features = false }
#utf8 path methods
camino = { version = "1.2.5", default-features = false, features = ["serde1"] }
#faster sync primitives
parking_lot = { version = "0.12.5", default-features = false, features = ["hardware-lock-elision", "deadlock_detection"] }
#easy parallelisation
rayon = { version = "1.12.0", default-features = false }
#faster sets and hashmaps
rustc-hash = { version = "2.1.3", default-features = false, features = ["std"] }
#load config from file
serde = { version = "1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
#querying ram usage 
sysinfo = { version = "0.39.6", default-features = false, features = ["system"] }
#better channel semantics
crossbeam = { version = "0.8.5", default-features = false, features = ["std", "crossbeam-channel"] }
#lru tracking
lru = { version = "0.18.4", features = ["hashbrown"] }
#faster allocator (by default we get way too much churn)
mimalloc = { version = "0.1.52", default-features = false, features = ["override", "v2", "win_direct_tls"] }

##media stuff
#serialising video cache files
bincode = { version = "=2", default-features = false, features = ["std", "derive"] }
#reading videos
ffmpeg-next = { version = "9.0.0", default-features = false, features = ["codec", "format", "filter", "software-scaling"] }
#querying video CFR metadata
ffprobe = { version = "0.4.0", default-features = false }
#reading images
image = { version = "0.25.10", default-features = false, features = ["bmp", "gif", "ico", "jpeg", "png", "webp"] }
#constant time hashing of videos for caching
imohash = { version = "0.1.2", default-features = false }
#k-d tree for fast matching
kiddo = { version = "6.3.0", default-features = false }
#convert images to YUV
yuv = { version = "0.8.17", default-features = false, features = ["sse", "avx", "fast_mode"] }
#fast image resize
fast_image_resize = { version = "6.1.0", default-features = false, features = ["std", "image"] }

##gpu/windowing stuff
#writing wgpu buffers
bytemuck = { version = "1.25.2", default-features = false }
#for wgpu querying
pollster = { version = "1.0.1", default-features = false }
#harness the gpu
wgpu = { version = "30.0.1", default-features = false, features = ["std", "wgpu-core", "wgsl", "parking_lot", "vulkan", "dx12", "gles", "serde"] }
#windowing wrapper
winit = { version = "0.30.13", default-features = false, features = ["rwh_06"] }
#file dialog / show panic in a message box
rfd = { version = "0.17.2", default-features = false }